#!/bin/bash
echo "host:"
hostname
echo "IPs:"
hostname -i
hostname -I
echo "network device:"
lspci | egrep -i --color 'network|ethernet'
ping -c 5 192.168.1.11

value=$( grep -ic "192.168.1.11	student" /etc/hosts )
if [ $value -eq 1 ]
then 
echo "user already exists"
else
echo "192.168.1.11	student">> /etc/hosts
fi

